name: Kakuyomu Downloader

on:
  schedule:
    - cron: "0 0 * * *"  # 毎日0時に実行（日本時間の午前0時）
  workflow_dispatch:

jobs:
  download:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up rclone
        run: |
          # rcloneのインストール
          curl https://rclone.org/install.sh | sudo bash
          mkdir -p ~/.config/rclone
          # rclone.confをGitHubリポジトリのrootから読み込む
          cp $GITHUB_WORKSPACE/rclone.conf ~/.config/rclone/rclone.conf

      - name: Clear HTTP cache
        run: |
          # インターネットのキャッシュを削除
          rm -rf ~/.cache

      - name: Install Python dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip install beautifulsoup4 requests

      - name: Run kakuyomu downloader
        run: |
          python3 kakuyomu/download_kakuyomu.py

      - name: Upload history file to Google Drive
        run: |
          # rcloneコマンドでファイルをGoogle Driveのルート直下に上書き
          rclone move kakuyomu/カクヨムダウンロード経歴.txt drive:/カクヨムダウンロード経歴.txt --transfers=1 --progress
