# .github/workflows/daily_downloader.yml
name: Daily Novel Downloader

on:
  schedule:
    - cron: '0 15 * * *'  # JST 0:00 (UTC+9)
  workflow_dispatch:     # 手動実行も可能にする

jobs:
  download:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip

      - name: Set up rclone
        run: |
          mkdir -p ~/.config/rclone
          cp rclone.conf ~/.config/rclone/rclone.conf

      - name: Run novel downloader
        run: python novel_downloader.py
