name: Kakuyomu Downloader

on:
  schedule:
    - cron: "0 0 * * *"  # 毎日0時に実行
  workflow_dispatch:

jobs:
  download:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up rclone
        run: |
          curl https://rclone.org/install.sh | sudo bash
          mkdir -p ~/.config/rclone
          cp ./rclone.conf ~/.config/rclone/rclone.conf  # リポジトリのrclone.confを配置

      - name: Install Python dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip install beautifulsoup4 requests

      - name: Run kakuyomu downloader
        run: |
          python3 kakuyomu/download_kakuyomu.py

      - name: Upload history file to Google Drive
        run: |
          rclone move kakuyomu/カクヨムダウンロード経歴.txt drive:/カクヨムダウンロード経歴.txt --transfers=1 --progress
